# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabrielb/Bureau/bsdmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabrielb/Bureau/bsdmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabrielb/Bureau/bsdmake/CMakeFiles /home/gabrielb/Bureau/bsdmake//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabrielb/Bureau/bsdmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named make

# Build rule for target.
make: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 make
.PHONY : make

# fast build rule for target.
make/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/build
.PHONY : make/fast

arch.o: arch.c.o
.PHONY : arch.o

# target to build an object file
arch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/arch.c.o
.PHONY : arch.c.o

arch.i: arch.c.i
.PHONY : arch.i

# target to preprocess a source file
arch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/arch.c.i
.PHONY : arch.c.i

arch.s: arch.c.s
.PHONY : arch.s

# target to generate assembly for a file
arch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/arch.c.s
.PHONY : arch.c.s

buf.o: buf.c.o
.PHONY : buf.o

# target to build an object file
buf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/buf.c.o
.PHONY : buf.c.o

buf.i: buf.c.i
.PHONY : buf.i

# target to preprocess a source file
buf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/buf.c.i
.PHONY : buf.c.i

buf.s: buf.c.s
.PHONY : buf.s

# target to generate assembly for a file
buf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/buf.c.s
.PHONY : buf.c.s

cond.o: cond.c.o
.PHONY : cond.o

# target to build an object file
cond.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/cond.c.o
.PHONY : cond.c.o

cond.i: cond.c.i
.PHONY : cond.i

# target to preprocess a source file
cond.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/cond.c.i
.PHONY : cond.c.i

cond.s: cond.c.s
.PHONY : cond.s

# target to generate assembly for a file
cond.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/cond.c.s
.PHONY : cond.c.s

dir.o: dir.c.o
.PHONY : dir.o

# target to build an object file
dir.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/dir.c.o
.PHONY : dir.c.o

dir.i: dir.c.i
.PHONY : dir.i

# target to preprocess a source file
dir.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/dir.c.i
.PHONY : dir.c.i

dir.s: dir.c.s
.PHONY : dir.s

# target to generate assembly for a file
dir.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/dir.c.s
.PHONY : dir.c.s

for.o: for.c.o
.PHONY : for.o

# target to build an object file
for.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/for.c.o
.PHONY : for.c.o

for.i: for.c.i
.PHONY : for.i

# target to preprocess a source file
for.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/for.c.i
.PHONY : for.c.i

for.s: for.c.s
.PHONY : for.s

# target to generate assembly for a file
for.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/for.c.s
.PHONY : for.c.s

hash.o: hash.c.o
.PHONY : hash.o

# target to build an object file
hash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/hash.c.o
.PHONY : hash.c.o

hash.i: hash.c.i
.PHONY : hash.i

# target to preprocess a source file
hash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/hash.c.i
.PHONY : hash.c.i

hash.s: hash.c.s
.PHONY : hash.s

# target to generate assembly for a file
hash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/hash.c.s
.PHONY : hash.c.s

hash_tables.o: hash_tables.c.o
.PHONY : hash_tables.o

# target to build an object file
hash_tables.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/hash_tables.c.o
.PHONY : hash_tables.c.o

hash_tables.i: hash_tables.c.i
.PHONY : hash_tables.i

# target to preprocess a source file
hash_tables.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/hash_tables.c.i
.PHONY : hash_tables.c.i

hash_tables.s: hash_tables.c.s
.PHONY : hash_tables.s

# target to generate assembly for a file
hash_tables.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/hash_tables.c.s
.PHONY : hash_tables.c.s

job.o: job.c.o
.PHONY : job.o

# target to build an object file
job.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/job.c.o
.PHONY : job.c.o

job.i: job.c.i
.PHONY : job.i

# target to preprocess a source file
job.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/job.c.i
.PHONY : job.c.i

job.s: job.c.s
.PHONY : job.s

# target to generate assembly for a file
job.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/job.c.s
.PHONY : job.c.s

lst.o: lst.c.o
.PHONY : lst.o

# target to build an object file
lst.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/lst.c.o
.PHONY : lst.c.o

lst.i: lst.c.i
.PHONY : lst.i

# target to preprocess a source file
lst.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/lst.c.i
.PHONY : lst.c.i

lst.s: lst.c.s
.PHONY : lst.s

# target to generate assembly for a file
lst.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/lst.c.s
.PHONY : lst.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/main.c.s
.PHONY : main.c.s

make.o: make.c.o
.PHONY : make.o

# target to build an object file
make.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/make.c.o
.PHONY : make.c.o

make.i: make.c.i
.PHONY : make.i

# target to preprocess a source file
make.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/make.c.i
.PHONY : make.c.i

make.s: make.c.s
.PHONY : make.s

# target to generate assembly for a file
make.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/make.c.s
.PHONY : make.c.s

parse.o: parse.c.o
.PHONY : parse.o

# target to build an object file
parse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/parse.c.o
.PHONY : parse.c.o

parse.i: parse.c.i
.PHONY : parse.i

# target to preprocess a source file
parse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/parse.c.i
.PHONY : parse.c.i

parse.s: parse.c.s
.PHONY : parse.s

# target to generate assembly for a file
parse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/parse.c.s
.PHONY : parse.c.s

proc.o: proc.c.o
.PHONY : proc.o

# target to build an object file
proc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/proc.c.o
.PHONY : proc.c.o

proc.i: proc.c.i
.PHONY : proc.i

# target to preprocess a source file
proc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/proc.c.i
.PHONY : proc.c.i

proc.s: proc.c.s
.PHONY : proc.s

# target to generate assembly for a file
proc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/proc.c.s
.PHONY : proc.c.s

shell.o: shell.c.o
.PHONY : shell.o

# target to build an object file
shell.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/shell.c.o
.PHONY : shell.c.o

shell.i: shell.c.i
.PHONY : shell.i

# target to preprocess a source file
shell.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/shell.c.i
.PHONY : shell.c.i

shell.s: shell.c.s
.PHONY : shell.s

# target to generate assembly for a file
shell.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/shell.c.s
.PHONY : shell.c.s

str.o: str.c.o
.PHONY : str.o

# target to build an object file
str.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/str.c.o
.PHONY : str.c.o

str.i: str.c.i
.PHONY : str.i

# target to preprocess a source file
str.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/str.c.i
.PHONY : str.c.i

str.s: str.c.s
.PHONY : str.s

# target to generate assembly for a file
str.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/str.c.s
.PHONY : str.c.s

suff.o: suff.c.o
.PHONY : suff.o

# target to build an object file
suff.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/suff.c.o
.PHONY : suff.c.o

suff.i: suff.c.i
.PHONY : suff.i

# target to preprocess a source file
suff.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/suff.c.i
.PHONY : suff.c.i

suff.s: suff.c.s
.PHONY : suff.s

# target to generate assembly for a file
suff.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/suff.c.s
.PHONY : suff.c.s

targ.o: targ.c.o
.PHONY : targ.o

# target to build an object file
targ.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/targ.c.o
.PHONY : targ.c.o

targ.i: targ.c.i
.PHONY : targ.i

# target to preprocess a source file
targ.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/targ.c.i
.PHONY : targ.c.i

targ.s: targ.c.s
.PHONY : targ.s

# target to generate assembly for a file
targ.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/targ.c.s
.PHONY : targ.c.s

util.o: util.c.o
.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/util.c.s
.PHONY : util.c.s

var.o: var.c.o
.PHONY : var.o

# target to build an object file
var.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/var.c.o
.PHONY : var.c.o

var.i: var.c.i
.PHONY : var.i

# target to preprocess a source file
var.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/var.c.i
.PHONY : var.c.i

var.s: var.c.s
.PHONY : var.s

# target to generate assembly for a file
var.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make.dir/build.make CMakeFiles/make.dir/var.c.s
.PHONY : var.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... make"
	@echo "... arch.o"
	@echo "... arch.i"
	@echo "... arch.s"
	@echo "... buf.o"
	@echo "... buf.i"
	@echo "... buf.s"
	@echo "... cond.o"
	@echo "... cond.i"
	@echo "... cond.s"
	@echo "... dir.o"
	@echo "... dir.i"
	@echo "... dir.s"
	@echo "... for.o"
	@echo "... for.i"
	@echo "... for.s"
	@echo "... hash.o"
	@echo "... hash.i"
	@echo "... hash.s"
	@echo "... hash_tables.o"
	@echo "... hash_tables.i"
	@echo "... hash_tables.s"
	@echo "... job.o"
	@echo "... job.i"
	@echo "... job.s"
	@echo "... lst.o"
	@echo "... lst.i"
	@echo "... lst.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... make.o"
	@echo "... make.i"
	@echo "... make.s"
	@echo "... parse.o"
	@echo "... parse.i"
	@echo "... parse.s"
	@echo "... proc.o"
	@echo "... proc.i"
	@echo "... proc.s"
	@echo "... shell.o"
	@echo "... shell.i"
	@echo "... shell.s"
	@echo "... str.o"
	@echo "... str.i"
	@echo "... str.s"
	@echo "... suff.o"
	@echo "... suff.i"
	@echo "... suff.s"
	@echo "... targ.o"
	@echo "... targ.i"
	@echo "... targ.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... var.o"
	@echo "... var.i"
	@echo "... var.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

